### ISSUE TITLE
How am I supposed to Fork inside a callback?

### ISSUE THREAD

**Issue by toddbruner** [karupanerura/p5-AnyEvent-ForkManager#8]
Please see http://stackoverflow.com/questions/39337677/anyeventstompclient-anyeventforkmanger-intermittent-error

for a description of the problem and a test program.  Am I doing this wrong or could something else be going on?

thanks,

**Comment by karupanerura** [comment]
@toddbruner Sorry for late the reply.

You should handle the exception in your `AnyEvent::ForkManager->start` callback.
Because Object::Event ignores the uncaught exception in the callback. And it continues AnyEvent's event loop.
So in this case, if some exception has occurred in the child process, the event loop continues on the child process too. actually, the child process's event loop receives an event form MQ, and it will always fail.
You have to catch all exceptions in your callback.
